### ISSUE TITLE
roundcube library missing

### ISSUE THREAD

**Issue by DDevine** [RepRapMorgan/lilian#1]
Where can I find roundcube.scad?

**Comment by qharley** [comment]
Repaired... 

roundcube.scad is one of my old faithful private library modules, and is now added in the source/lib folder.  Add it to your Openscad library folder.

**Comment by DDevine** [comment]
You don't seem to have committed the change to the public repo.

**Comment by qharley** [comment]
I will give it another go

**Comment by qharley** [comment]
Try now.

**Comment by DDevine** [comment]
Seems to compile fine and roundcube.scad is there so thanks!
