### ISSUE TITLE
Missing module files

### ISSUE THREAD

**Issue by The3rdIcon** [RepRapMorgan/lilian#2]
When trying to generate part 4 you get a warning saying WARNING: Ignoring unknown module 'polyhole2'

I checked different versions of MCAD and wasn't able to find one that had a polyhole.scad with a polyhole2 module in it.

This seem to prevent the hole from forming on part 4 since it doesn't look like the stl file provided.

**Comment by qharley** [comment]
I added the module to the source file.  It lives on my system as a custom library.
